### ISSUE TITLE
LOCO data eval

### ISSUE THREAD

**Issue by anewcatwhy** [drsaqibbhatti/EfficientAD#1]
hello author,i want to know how to eval the LOCO data successfully
do you get it?
thanks for reading

**Comment by drsaqibbhatti** [comment]
As already mentioned in the readme file

Use the following link for evaluation:

https://www.mydrive.ch/shares/60736/698155e0e6d0467c4ff6203b16a31dc9/download/439517473-1665667812/mvtec_ad_evaluation.tar.xz

**Comment by anewcatwhy** [comment]
thanks for your Reply，i have the error OSerror：“good\000.tiff” mismatches  with the code “good/”
i don‘t know the reason
